export const COMPONENTS = {
    HEADER: "header",
    SIDEBAR: "sidebar",
    FOOTER: "footer",
    DETAILS: "details",
    ACTIVITY: "activity",
    DISPUTE: "dispute",
    DISPUTE_MAIL: "dispute-mail",
    SPAM_MAIL: "spam-mail",
    REGISTRATION: "registration",
    TABLE: "table",
    STATUS_CHIP: "status_chip",
    VIEW_BUTTON: "view_button",
    VIEW_DETAIL: "view_detail",
  };